### PR TITLE
change content and reply data to type any

### PR DESCRIPTION
**Pull request by mellistibco**
this should address #222

### CODE REVIEW

**Comment by mellistibco** [comment]
The reply code is:
```golang
json.NewEncoder(w).Encode(replyData)
```
I think that will still work for anything, string, etc. no?

**Comment by lixingwang** [comment]
https://github.com/TIBCOSoftware/flogo-contrib/blob/master/activity/reply/activity.go line 43

**Comment by mellistibco** [comment]
ahh, sorry, was just looking at the rest trigger... yup, should change that also

**Comment by mellistibco** [comment]
personally i feel we should just depreciate the legacy reply activity...

**Comment by mellistibco** [comment]
@lixingwang changed to TypeAny

**Pull request merged**
