### PR TITLE
Avoid to shceduleEval task while it is a skipped status

### PR DESCRIPTION
**Pull request by lixingwang**
This issue cause linker condition false but the branch flow also gets run.

### CODE REVIEW

**Comment by fm-tibco** [comment]
Does the branch execute activities or does it just go from task to task marking them skipped?

**Comment by fm-tibco** [comment]
It should preform skip propagation, means it should mark everything in the branch skipped

**Comment by fm-tibco** [comment]
I fixed an issue in the simple model that should handle skip on eval properly

**Comment by lixingwang** [comment]
FIxed at commit dc5ff77f48b4151e35d1ff7681fa23a9a90869f3 by Frank

**Pull request closed without merging**
